version: '3.7'
services:
  app:
    container_name: dnsmasq
    image: joaquinmonteroalvarezith/simple-dns:latest
    logging:
      options:
        max-size: 100m
    build:
      context: .
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 5380:8080
      - 53:53/udp
    env_file:
      - .env
    tty: true
    stdin_open: true
