version: '3.7'
services:
  app:
    container_name: dnsmasq
    image: joaquinmonteroalvarezith/simple-dns:latest
    build:
      context: .
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 5380:8080
      - 53:53
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
    tty: true
    stdin_open: true

